# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'StepWell' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
	pod 'FirebaseUI'
	pod 'FirebaseUI/Auth'


end
